apiVersion: v1
kind: Secret
metadata:
  name: scheduler-env
  namespace: scheduler
type: Opaque
stringData:
  APP_KEY: "base64:BsoMRGV/P9uBuaReqWiBI36V5pm6ReMtPTW0BJvRd5A="
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://scheduler.sviniabanditka.com"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "scheduler"
  DB_USERNAME: "scheduler"
  DB_PASSWORD: "scheduler_prod_2024"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CACHE_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SOLVER_URL: "http://solver:8081"
