<?php

namespace App\Http\Controllers;

use App\Models\Tenant;
use App\Models\User;
use App\Services\TenantManager;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;

class AuthController extends Controller
{
    public function showRegisterForm()
    {
        if (Auth::check()) {
            return redirect('/admin');
        }

        return view('auth.register');
    }

    public function register(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'confirmed', Password::min(8)],
            'university_name' => ['required', 'string', 'max:255'],
        ]);

        $user = DB::transaction(function () use ($request) {
            // Create tenant (slug auto-generated by Tenant model)
            $slug = Tenant::generateUniqueSlug($request->university_name);
            $tenant = Tenant::create([
                'name' => $request->university_name,
                'subdomain' => $slug,
                'domain' => $slug . '.' . config('app.url', 'scheduler.local'),
                'public_slug' => $slug,
                'is_active' => true,
            ]);

            // Create user as owner
            $user = User::withoutGlobalScopes()->create([
                'tenant_id' => $tenant->id,
                'name' => $request->name,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'role' => 'owner',
            ]);

            return $user;
        });

        Auth::login($user);

        // Set tenant in the manager
        $tenantManager = app(TenantManager::class);
        $tenantManager->setTenant($user->tenant);

        return redirect('/admin')->with('success', 'Реєстрація успішна! Ваш університет створено.');
    }

    public function showLoginForm()
    {
        if (Auth::check()) {
            return redirect('/admin');
        }

        return view('auth.login');
    }

    public function login(Request $request)
    {
        $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);

        if (Auth::attempt($request->only('email', 'password'), $request->boolean('remember'))) {
            $request->session()->regenerate();

            $user = Auth::user();
            $tenantManager = app(TenantManager::class);
            $tenantManager->setTenant($user->tenant);

            return redirect()->intended('/admin');
        }

        return back()->withErrors([
            'email' => 'Невірний email або пароль.',
        ])->onlyInput('email');
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        $tenantManager = app(TenantManager::class);
        $tenantManager->clearTenant();

        return redirect('/');
    }
}
